# Generated by Django 2.2 on 2020-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200306_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
    ]
